### ISSUE TITLE
Привет!

### ISSUE THREAD

**Issue by VladislavKrs** [Fedor-sherbanyuk/easyChat#2]
Привет. Твой код хорошо организован и чист, но есть вещи, которые можно улучшить.
Выделение компонентов: Для большей читабельности кода можешь создать отдельные компоненты для отдельных частей UI кода. Например, можно создать компоненты как  UserDropdown, MessageInput, SendMessageButton и MessageList.

**Comment by Fedor-sherbanyuk** [comment]
change
